update playwright-baseline

diff --git a/.github/workflows/playwright-baseline.yml b/.github/workflows/playwright-baseline.yml
--- a/.github/workflows/playwright-baseline.yml
+++ b/.github/workflows/playwright-baseline.yml
@@ -3,6 +3,8 @@ name: Playwright Baseline
 on:
   push:
     branches: [ master ]
+  workflow_dispatch:
+    branches: [ master ]
 
 permissions:
   contents: read
@@ -10,6 +12,9 @@ permissions:
 jobs:
   generate-baseline:
     runs-on: ubuntu-latest
+    defaults:
+      run:
+        working-directory: ./fe
     steps:
     - name: Checkout
       uses: actions/checkout@v4
@@ -19,7 +24,7 @@ jobs:
       with:
         node-version: 22.18.0
 
-    - name: Cache yarn dependencies
+    - name: Cache dependencies
       uses: actions/cache@v4
       id: yarn-cache
       with:
@@ -28,7 +33,6 @@ jobs:
 
     - name: Install dependencies
       if: steps.yarn-cache.outputs.cache-hit != 'true'
-      working-directory: ./fe
       run: yarn install --frozen-lockfile
 
     - name: Cache Playwright browsers
@@ -41,24 +45,34 @@ jobs:
           playwright-${{ runner.os }}-
 
     - name: Install Playwright browsers and dependencies
-      working-directory: ./fe
       run: |
         if [ "${{ steps.playwright-cache.outputs.cache-hit }}" != "true" ]; then
-          echo "Cache miss - installing browsers and dependencies"
-          npx playwright install --with-deps
+          npx playwright install --with-deps > /dev/null # --quiet
         else
-          echo "Cache hit - installing only system dependencies"
-          npx playwright install-deps
+          npx playwright install-deps > /dev/null # --quiet
         fi
 
     - name: Generate baseline screenshots
-      working-directory: ./fe
-      run: npx playwright test --update-snapshots
+      run: |
+        npx playwright test --update-snapshots
 
     - name: Upload baseline snapshots as artifact
       uses: actions/upload-artifact@v4
       with:
         name: playwright-baseline-snapshots
-        path: fe/.tests/snaps/
-        retention-days: 90
-        overwrite: true  # Replaces previous artifact with same name
+        path: .tests/snaps/
+        retention-days: 60
+        overwrite: true
+
+    - name: Add summary
+      if: always()
+      # add artifact download link to the summary
+      run: |
+        if [ $? -ne 0 ]; then
+          echo "### ❌ Playwright Baseline Generation Failed" >> $GITHUB_STEP_SUMMARY
+          echo "Check the logs for details." >> $GITHUB_STEP_SUMMARY
+        else
+          echo "### ✅ Baseline snapshots have been updated and stored as an artifact" >> $GITHUB_STEP_SUMMARY
+          echo "Link: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}#artifacts" >> $GITHUB_STEP_SUMMARY
+        fi
+        echo "" >> $GITHUB_STEP_SUMMARY
